config/routes.rb
Rails.application.routes.draw do
  resources :photos do
    resources :comments
  end

  devise_for :users
  get '/user_photos', to: 'photos#user_photos'

get 'users/:id/uploads/', to: 'users#uploads', as: 'uploads_user'

  root 'photos#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :picture, PictureUploader

  scope :search, ->(keyword){ where('lower(title) LIKE ?', "%#{keyword}%") if keyword.present? }
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :photos
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.create(comment_params)
    @comment.update(user_id: current_user.id) if current_user
    redirect_to photo_path(@photo)
  end

  def destroy
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.find(params[:id])
    @comment.destroy
    redirect_to photo_path(@photo)
  end

  def show
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :photo_id)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  def index
    @photos = Photo.search(params[:keyword])
  end

  def show
    respond_to do |format|
      format.html
      format.json { render :json => @photo.to_json}
    end
  end

  def new
    @photo = Photo.new
  end

  def edit
  end

  def create

    @photo = current_user.photos.create(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def photo_params
      params.require(:photo).permit(:title, :picture, :user_id, :url)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def uploads
  @user = User.find(params[:id])
  @photos = @user.photos
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% if comment.persisted? %>

<div class="row">
  <h3><%= comment.user.email if comment.user_id %> : <%= comment.body %> | <%=  time_ago_in_words(comment.created_at) %> ago<h3>
</div>

<% end %>

app/views/comments/_form.html.erb
<h2>Leave your thoughts:</h2>
  <%= form_for([@photo, @photo.comments.new]) do |f| %>
    <%= f.text_field :body %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loadnseek</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<body>
  <div class="row well topofpage">
    <div class="col-md-4 text-left">
      <p class="loggedin"><% if user_signed_in? %> Logged In</p>
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
      <% end %>
    </div>
    <div class="col-md-8 text-left">
      <p><h4 class="weather"></h4><span class="weather-icon"></span></p>
    </div>
  </div>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-3">
      <form>
        <legend class="search">Search by picture title:</legend>
          <input id="search" type="text" class="form-control" value="<%= params[:keyword] %>" name="keyword" placeholder="keyword">
      </form>
    </div>
  </div>
</div>

<div class="row text-right">
  <%= link_to 'New Photo', new_photo_path %>
</div>

<hr class="featurette-divider"></hr>

<section id="photos-section">
<div class="container story_pics">
  <% @photos.in_groups_of(4) do |group| %>
    <div class="row">
      <% group.compact.each do |photo| %>
        <div class="col-md-3 photoindex">
          <%= link_to image_tag(photo.picture_url(:thumb), id: photo.id, class:"img-responsive photo-index"), photo%>
          <%= content_tag(:p, photo.title, class:"title-pop") %>
          <% link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
</section>

<hr class="featurette-divider"></hr>

<div id="content" style="height: 200px;"></div>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<div class="row">
  <h3><small>Title:  </small><%= content_tag(:p, @photo.title, class: "title-pop") %>
  <small>User:  </small><%= link_to @photo.user.email, uploads_user_path(@photo.user_id) %></h3>
<div class="row">

<section id="large-photo">
  <div>
    <p><%= image_tag(@photo.picture) %><p>
  </div>
</section>

  <p><%= render 'comments/form' %></p>

  <p><%= render @photo.comments %></p>

<p><%= link_to 'Edit', edit_photo_path(@photo) %> | <%= link_to 'Back', photos_path %> </p>

app/views/photos/user_photos.html.erb
<div class="container story_pics">
  <% @photos.each do |photo| %>
    <%= image_tag photo.picture %>
  <% end %>
</div>
  <% end %>

<%= link_to 'Back', photos_path %>

<% @users.each do |user| %>
  <%= user.email %>
<% end %>

app/views/users/uploads.html.erb
<div class="container story_pics">
  <% @photos.each do |photo| %>
    <%= image_tag photo.picture %>
  <% end %>
</div>

<%= link_to 'Back', photos_path %>